#!/bin/bash
#
# cdist-inventory
#
# Automatically generate a cdist inventory based on explorer output.

CFG=~/.cdist-inventory.ini

parse_config() {
   count=0
   while read var
   do
      if [[ $var == \[*] ]]
      then
          if test "$section" != ""; then
             declare -g -A "explorers[$section]=$list"
             unset list
          fi
          section=${var:1:-1}
      else
          declare -g -A "actions[$count]=$var"
          list="$list $count"
          count=$(($count + 1))
      fi
   done < <( grep -v -e "^$" -e "^#" $CFG )
   test "$section" != "" && declare -g -A "explorers[$section]=$list"
}

inventory() {
   host=$1

   for explorer in ${!explorers[*]}
   do
      if test -f "$CDIST_EXPLORE/$host/$explorer"; then
         for action in ${explorers[$explorer]}
         do
            op=${actions[$action]/:*}
            arg=${actions[$action]/*:}
            case $op in
            "if")
               content=${arg/=*/}
               value=${arg/*=/}
               grep $content $CDIST_EXPLORE/$host/$explorer > /dev/null 2>&1 && echo $value >> $CDIST_INVENTORY/$host
            ;;
            "content")
               case $arg in
               "copy")
                  cat $CDIST_EXPLORE/$host/$explorer >> $CDIST_INVENTORY/$host
               ;;
               esac
            ;;
            esac
         done
      fi
   done
}

main() {
   test "$CDIST_EXPLORE" = "" && { echo "CDIST_EXPLORE not set, aborting."; exit 1; }
   test "$CDIST_INVENTORY" = "" && { echo "CDIST_INVENTORY not set, aborting."; exit 1; }
   test -f $CFG || { echo "Can't read configfile $CFG, aborting."; exit; }

   parse_config

   rm -rf $CDIST_INVENTORY
   mkdir -p $CDIST_INVENTORY

   for folder in $CDIST_EXPLORE/*
   do
      if test -d $folder
      then
         host=${folder/*\//}
         inventory $host
      fi
   done
}

main "$@"
