#!/bin/bash
#
# Verify if ssh keys are available in agent
#

test -e ~/.cdistrc && . ~/.cdistrc
ssh-add -L > /dev/null 2>&1
res=$?
if test "$res" -ne "2"; then
   numkeys=$(gpg-connect-agent -q 'keyinfo --list' /bye 2> /dev/null | grep '^S' | wc -l)
   openkeys=$(gpg-connect-agent -q 'keyinfo --list' /bye 2> /dev/null | grep '^S' | grep ' 1 ' | wc -l)
   test "$openkeys" -ne "$numkeys" && res=1
fi

case "$1" in
"-c")
   case "$res" in
   2) echo "No agent running"
   ;;
   1) echo "No keys open"
   ;;
   esac
;;
*)
   add=0
   test "$res" -eq "2" && { add=1; gpg-agent --daemon > /dev/null ; }
   keys=$(gpg-connect-agent 'keyinfo --list' /bye | grep '^S' | cut -d ' ' -f 3)
   test "$res" -eq "1" -o "$add" -eq "1" && { read -s -p "Passphrase: " pp; for key in $keys; do echo $pp | /usr/lib/gnupg2/gpg-preset-passphrase --preset $key; done; echo; }
;;
esac
