#!/bin/bash
#
# cdist-inventory
#
# Automatically generate a cdist inventory based on explorer output.

CFG=~/.cdist-inventory.ini
MANUALCFG=~/cdist-inventory

parse_config() {
   count=0
   while read var; do
      if [[ $var == \[*] ]]; then
          if test "$section" != ""; then
             declare -g -A "explorers[$section]=$list"
             unset list
          fi
          section=${var:1:-1}
          test "${explorers[$section]}" != "" && echo "Duplicate header \"$section\" in config."
      else
          declare -g -A "actions[$count]=$var"
          list="$list $count"
          count=$(($count + 1))
      fi
   done < <( grep -v -e "^$" -e "^#" $CFG )
   test "$section" != "" && declare -g -A "explorers[$section]=$list"
}

inventory() {
   host=$1

   for explorer in ${!explorers[*]}; do
      ! test -e "$CDIST_EXPLORE/$host/$explorer" -o \
              -e "$MANUALCFG/$explorer" && continue
      for action in ${explorers[$explorer]}; do
         tag=""
         for ops in ${actions[$action]//+/ }; do
            op=${ops/:*}
            arg=${ops/*:}
            case $op in
            "if")
               content=${arg/=*/}
               neg=0
               test "${content:0:1}" = "!" && neg=1
               value=${arg/*=/}
               if test -e "$CDIST_EXPLORE/$host/$explorer"; then
                  match="$(grep $content $CDIST_EXPLORE/$host/$explorer 2> /dev/null)"
                  test "$neg" -eq 0 -a "$match" != "" && {
                     if test "${value:0:1}" = "~"; then
                        match=$(echo $match | sed "${value:1}")
                     else
                        match="$value"
                     fi
                     tag="${tag}${match}"
                  }
                  test "$neg" -eq 1 -a "$match" = "" && \
                     tag="${tag}${value}"
               fi
               if test -e  "$MANUALCFG/$explorer"; then
                  if test "$neg" = 0; then
                     grep "$host" $MANUALCFG/$explorer > /dev/null 2>&1 && tag="${tag}${value}"
                  else
                     grep "$host" $MANUALCFG/$explorer > /dev/null 2>&1 || tag="${tag}${value}"
                  fi
               fi
            ;;
            "static")
               tag="${tag}${arg}"
            ;;
            "content")
               case $arg in
               "copy")
                  if test -e "$CDIST_EXPLORE/$host/$explorer"; then
                     tag="${tag}$(cat $CDIST_EXPLORE/$host/$explorer)"
                  fi
                  if test -e "$MANUALCFG/$explorer"; then
                     grep "$host" $MANUALCFG/$explorer > /dev/null 2>&1 && tag="${tag}true" || tag="${tag}false"
                  fi
               ;;
               ~*)
                  tag="${tag}$(sed "$arg" $CDIST_EXPLORE/$host/$explorer)"
               ;;
               esac
            ;;
            *)
               echo "Unknown operator: $op"
            ;;
            esac
         done
         test "$tag" != "" && echo "$tag" >> $CDIST_INVENTORY/$host
      done
   done
}

main() {
   test "$CDIST_EXPLORE" = "" && { echo "CDIST_EXPLORE not set, aborting."; exit 1; }
   test "$CDIST_INVENTORY" = "" && { echo "CDIST_INVENTORY not set, aborting."; exit 1; }
   test -f $CFG || { echo "Can't read configfile $CFG, aborting."; exit; }

   parse_config

   rm -rf $CDIST_INVENTORY
   mkdir -p $CDIST_INVENTORY

   for folder in $CDIST_EXPLORE/*; do
      if test -d $folder; then
         host=${folder/*\//}
         inventory $host
      fi
   done
   return 0
}

main "$@"
