#!/bin/bash
#
# Add explore output to git repository and push to origin
#

test -d "$CDIST_EXPLORE" || { echo "No explore directory found."; exit 1; }
type git > /dev/null 2>&1 || { echo "Git not found."; exit 1; }

cd "$CDIST_EXPLORE"

git status > /dev/null 2>&1
test "$?" -ne "0" && { echo "git status: non zero exit code."; exit 1; }

git add . > /dev/null 2>&1
test "$?" -ne "0" && { echo "git add: non zero exit code."; exit 1; }

git diff-index --quiet HEAD -- > /dev/null 2>&1
test "$?" -eq "0" && exit 0

date=$( date "+%Y%m%d-%H%M" )
git commit -am "$date $GIT_AUTHOR_NAME ($GIT_AUTHOR_EMAIL): $1" > /dev/null 2>&1
test "$?" -ne "0" && { echo "git commit: non zero exit code."; exit 1; }

git push > /dev/null 2>&1
test "$?" -ne "0" && { echo "Explore directory: git push non zero exit code."; exit 1; }
