#!/bin/bash
#
# Wrapper to make it easier to run cdist

# required for inventory option
export CDIST_BETA=1

usage()
{
   echo "runcdist [options] <hosts|tags>"
   echo
   echo "  <hosts>            Name of host or hosts to run cdist on"
   echo "  <tags>             Name of tag or tags to select hosts to run cdist on"
   echo "  -v                 Run verbose (more increases verbosity)"
   echo "  -q                 Quiet"
   echo "  -p                 Run in parrallel"
   echo "  -o <manifest>      Overrule default manifest with specific manifest"
   echo "  -t                 All non option arguments are tags. Runs against all hosts having all tags"
   echo "  -T                 All non option arguments are tags. Runs against all hosts having any tags"
   echo "  -l                 When no tags are specified, list all available tags. When tags are present, list all hosts having all tags"
   echo "  -L                 When no tags are specified, list all available tags. When tags are present, list all hosts having any tags"
   echo "  -a                 Run cdist on all hosts in inventory"
   exit 1
}

main()
{
   args="$@"
   verbose="-v"
   numargs=$#

   while getopts :hvqpto:alL opt; do
      case $opt in
      h) usage
      ;;
      v) verbose="$verbose -v"
      ;;
      q) verbose=""
      ;;
      p) par="-p 5"
      ;;
      t) tag="-t"
      ;;
      o) CONFIGTYPE=$OPTARG
      ;;
      a) all="-A"
      ;;
      l) list="all"
      ;;
      L) list="any"
      ;;
      \?) echo "Unknown option: -$OPTARG"
          usage
      ;;
      :) echo "Option -$OPTARG requires argument"
         usage
      ;;
      esac
   done
   shift $((OPTIND-1))
   items="$*"

   if test "$list" != ""; then
      if test "$items" = ""; then
         cdist inventory list | cut -d' ' -f2 | tr ',' '\n' | sort -u
         exit
      fi
      arg="-a"
      test "$list" = "any" && arg=""
      cdist inventory list $arg -H -t $items
      exit
   fi

   test "$items" = "" -a "$all" = "" && { echo "Either require all or inventory tag or hosts."; usage; }
   test "$items" != "" -a "$all" != "" && { echo "Can't choose all and specific hosts or inventory tags."; usage; }
   test "$tag" != "" -a "$all" != "" && { echo "Can't choose all and specific inventory tags"; usage; }
   test "$tag" != "" -a "$items" = "" && { echo "Can't choose tags and not specify them."; usage; }

   CDISTACTION=$CONFIGTYPE cdist config -c ~cdist/config -l-1 \
      $verbose $par $all $tag $items
   type cdist-explore-git > /dev/null 2>&1 && cdist-explore-git "$0 $args"
}

main "$@"
